# Generated by Django 4.1.5 on 2023-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stat_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField()),
                ("game", models.IntegerField()),
                ("huay", models.IntegerField()),
                ("muay", models.IntegerField()),
                ("ball", models.IntegerField()),
                ("bacara", models.IntegerField()),
                ("sms", models.IntegerField()),
                ("sex", models.CharField(max_length=3)),
                ("age", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
