# Generated by Django 4.1.5 on 2023-01-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0005_alter_stat_user_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat_user",
            name="tel",
            field=models.CharField(default="081xxxxxxx", max_length=10),
        ),
    ]
