# Generated by Django 4.1.5 on 2023-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0006_alter_stat_user_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat_user",
            name="age",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="bacara",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="ball",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="game",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="huay",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="muay",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="slot",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="sms",
            field=models.CharField(max_length=3),
        ),
    ]
