# Generated by Django 4.1.5 on 2023-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0007_alter_stat_user_age_alter_stat_user_bacara_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat_user",
            name="age",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="bacara",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="ball",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="game",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="huay",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="muay",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="sex",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="slot",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stat_user",
            name="sms",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
