# Generated by Django 4.1.5 on 2023-01-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0008_alter_stat_user_age_alter_stat_user_bacara_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stat_user",
            name="user",
        ),
        migrations.AddField(
            model_name="stat_user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
