# Generated by Django 4.1.5 on 2023-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientApp", "0009_remove_stat_user_user_stat_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
